In [10]:
from keras.models import Sequential
from keras.layers import *
import numpy as np

m = Sequential()

#Architektura 1
#m.add(Dense(2,input_dim=2, activation='tanh'))
#m.add(Dense(12,input_dim=2, activation='tanh'))
#m.add(Activation('tanh'))

#Architektura 2
m.add(Dense(6,input_dim=2, activation='tanh'))
m.add(Dense(20,input_dim=2, activation='tanh'))

m.add(Dense(1,activation='sigmoid'))

#m.add(Activation('sigmoid'))

X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y = np.array([[0],[1],[1],[0]],'float32')
m.compile(optimizer='adam',loss='binary_crossentropy')

print('Default')
m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
print(m.predict(X))

#Bramka OR
print('Bramka OR')
X1 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y1 = np.array([[0],[1],[1],[1]],'float32')

m.fit(X1,Y1,batch_size=1,epochs=200,verbose=0)
print(m.predict(X1))

#Bramka NOR
X2 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y2 = np.array([[1],[0],[0],[0]],'float32')

print('Bramka NOR')
m.fit(X2,Y2,batch_size=1,epochs=200,verbose=0)
print(m.predict(X2))

#Bramka AND
X3 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y3 = np.array([[0],[0],[0],[1]],'float32')

print('Bramka AND')
m.fit(X3,Y3,batch_size=1,epochs=200,verbose=0)
print(m.predict(X3))

#Bramka NAND
X4 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
Y4 = np.array([[1],[1],[1],[0]],'float32')

print('Bramka NAND')
m.fit(X4,Y4,batch_size=1,epochs=200,verbose=0)
print(m.predict(X4))




Default
1/1 [==============================] - 0s 56ms/step
[[0.4096483 ]
 [0.5572751 ]
 [0.5927199 ]
 [0.50564224]]
Bramka OR
1/1 [==============================] - 0s 21ms/step
[[0.09727065]
 [0.9473097 ]
 [0.95280844]
 [0.9762549 ]]
Bramka NOR
1/1 [==============================] - 0s 22ms/step
[[0.71349114]
 [0.08912912]
 [0.08464503]
 [0.03672649]]
Bramka AND
1/1 [==============================] - 0s 22ms/step
[[0.07079042]
 [0.11911006]
 [0.13691007]
 [0.511803  ]]
Bramka NAND
1/1 [==============================] - 0s 21ms/step
[[0.8524596 ]
 [0.82324183]
 [0.7818154 ]
 [0.5395298 ]]
